title: blog
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://MaBlock.github.io"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://github.com/xiaomin7"
footer_text: " "

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"

theme: jekyll-theme-architect